import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

const root = process.cwd();
const policyPath = 'data/visual/all-character-garment-pattern-seam-closure-load-fidelity-master-v1.json';
const authorityPath = 'docs/visual/all-character-garment-pattern-seam-closure-load-fidelity-master-v1.md';
const productionPolicyPath = 'data/visual/character-production-generation-entrypoint-v1.json';
const profilePaths = ['data/visual/core5-living-visual-profiles-v1.json','data/visual/current21-extended-living-visual-profiles-v1.json','data/visual/future15-living-visual-profiles-v1.json'];
const fail = (m: string): never => { throw new Error(`[garment-construction] ${m}`); };
const policy = JSON.parse(readFileSync(resolve(root, policyPath), 'utf8'));
const authority = readFileSync(resolve(root, authorityPath), 'utf8');
const productionPolicy = JSON.parse(readFileSync(resolve(root, productionPolicyPath), 'utf8'));
if (policy.status !== 'CURRENT_PRODUCTION_VISUAL_AUTHORITY') fail('status invalid');
if (policy.scopeCount !== 36 || policy.assetKindCount !== 9) fail('scope must remain 36/9');
if (policy.production?.requiredForCandidateGeneration !== true) fail('production requirement weakened');
if (policy.production?.generatedOutputState !== 'CANDIDATE_REVIEW_REQUIRED') fail('candidate boundary weakened');
if (policy.production?.generatedGarmentConstructionCreatesCanon !== false) fail('canon guard weakened');
if ((policy.constructionAxes ?? []).length < 60) fail('60+ construction axes required');
if ((policy.constructionInvariants ?? []).length < 30) fail('30 construction invariants required');
if ((policy.preservationPriority ?? []).length < 12) fail('12 preservation priorities required');
if ((policy.forbiddenShortcuts ?? []).length < 60) fail('60+ forbidden shortcuts required');
if (policy.unknownConstructionDefault !== 'SOURCE_CONSTRAINED_MINIMUM_MECHANICALLY_VALID_GARMENT_COMPLETION') fail('unknown default weakened');
for (const [field, value] of Object.entries(policy.rules ?? {})) if (value !== false) fail(`rule must remain false: ${field}`);
if (!authority.includes('CANDIDATE_REVIEW_REQUIRED') || !authority.includes('SOURCE_CONSTRAINED_MINIMUM_MECHANICALLY_VALID_GARMENT_COMPLETION')) fail('authority boundary missing');
const ids: string[] = [];
for (const path of profilePaths) for (const c of JSON.parse(readFileSync(resolve(root, path), 'utf8')).characters ?? []) ids.push(c.id);
if (ids.length !== 36 || new Set(ids).size !== 36) fail(`expected 36 unique ids, got ${ids.length}/${new Set(ids).size}`);
const falseFields = Object.keys(policy.rules ?? {});
for (const id of ids) {
  const stdout = execFileSync(process.execPath, ['--experimental-strip-types', resolve(root, productionPolicy.productionExporter), '--character', id, '--kind', 'character_reference'], { cwd: root, encoding: 'utf8', maxBuffer: 224 * 1024 * 1024 });
  const output = JSON.parse(stdout);
  if (output.allCharacterGarmentPatternSeamClosureLoadFidelityRequired !== true) fail(`${id}: construction flag missing`);
  for (const field of falseFields) if (output[field] !== false) fail(`${id}: guard weakened: ${field}`);
  if ((output.garmentConstructionAxes ?? []).length < 60) fail(`${id}: axes missing`);
  if ((output.garmentConstructionPreservationPriority ?? []).length < 12) fail(`${id}: preservation priority missing`);
  if (output.generatedOutputState !== 'CANDIDATE_REVIEW_REQUIRED') fail(`${id}: candidate boundary weakened`);
  if (!output.authorityOrder?.includes(authorityPath) || !output.authorityOrder?.includes(policyPath)) fail(`${id}: authority chain missing`);
  if (!output.prompt?.includes('GARMENT PATTERN / SEAM / CLOSURE / LOAD FIDELITY — FINAL CONSTRUCTION TOPOLOGY LOCK.')) fail(`${id}: prompt block missing`);
}
console.log(`[garment-construction] OK: ${ids.length}/36 final production prompts preserve pattern/seam/closure/load topology`);
