import { readFileSync } from 'node:fs';
import { title1BaseWeaponRuntimeAdmissionSummary } from '../../src/game/data/title1BaseWeaponRuntimeAdmissionSource.ts';
function assert(condition: unknown, message: string): asserts condition { if (!condition) throw new Error(message); }
const battleSource = readFileSync(new URL('../../unity/VampPonUnity/Assets/_Project/Scripts/Runtime/U2BattleController.cs', import.meta.url), 'utf8');
const coordinatorSource = readFileSync(new URL('../../unity/VampPonUnity/Assets/_Project/Scripts/Runtime/Gameplay/Stage1GameplayRuntimeCoordinator.cs', import.meta.url), 'utf8');
const evidenceSource = readFileSync(new URL('../unity/u47-simulator-evidence-sources.ts', import.meta.url), 'utf8');
assert(battleSource.includes('public bool FireGameplayProjectileAtTarget('), 'targeted projectile primitive missing');
assert(battleSource.includes('U2EnemyActor target,'), 'targeted primitive must take typed enemy actor');
assert(battleSource.includes('EnemyStatusApplicationRequest? statusApplicationRequest = null'), 'targeted primitive must preserve Status transport');
assert(battleSource.includes('if (target == null || !target.IsTargetable) return false;'), 'targeted primitive must fail closed');
assert(battleSource.includes('var projectile = FirstInactive(projectiles);'), 'targeted primitive must reuse current pool');
assert(battleSource.includes('projectile.Activate(player.position, target, config.projectileSpeed, damage, pierce, statusApplicationRequest);'), 'targeted primitive must preserve current target-based architecture');
assert(battleSource.includes('return FireGameplayProjectileAtTarget(target, damage, pierce, statusApplicationRequest);'), 'nearest API must delegate to canonical target spawn');
assert(battleSource.match(/public bool FireGameplayProjectileAtTarget\(/g)?.length === 1, 'targeted spawn must have one implementation');
assert(battleSource.includes('FireGameplayProjectilesAtNearestTargets'), 'multi-target primitive must compose targeted spawn');
assert(coordinatorSource.includes('battle.FireGameplayProjectile(effect.damage * damageMultiplier, effect.pierce)'), 'live coordinator must remain nearest-target');
assert(!coordinatorSource.includes('FireGameplayProjectileAtTarget'), 'live coordinator must not choose explicit targets yet');
assert(evidenceSource.includes('PR169_PROJECTILE_RECOVERY_NORMALIZER'), 'U47 normalizer recovery marker missing');
assert(title1BaseWeaponRuntimeAdmissionSummary.unityAdmittedRuntimeCount === 0, 'targeted primitive alone must not admit Selected16');
console.log(JSON.stringify({ status: 'PASS', canonicalProjectileSpawnPrimitive: 'FireGameplayProjectileAtTarget', liveTargetSelection: 'nearest-target' }, null, 2));
