import { readFileSync } from 'node:fs'; import { resolve } from 'node:path'; import { execFileSync } from 'node:child_process';
const root=resolve(import.meta.dirname,'../..'); const read=(p:string)=>readFileSync(resolve(root,p),'utf8'); const json=(p:string)=>JSON.parse(read(p)); const check=(v:unknown,m:string)=>{if(!v)throw new Error(`U48 production connection check failed: ${m}`)};
const approved=json('docs/design-targets/generated/unity-u48/approved-production-set.json'); const readiness=json('docs/design-targets/generated/unity-u48/readiness.json');
const provider=read('unity/VampPonUnity/Assets/_Project/Scripts/Runtime/Visuals/RuntimeVisualAssetProvider.cs'); const binder=read('unity/VampPonUnity/Assets/_Project/Scripts/Runtime/Visuals/U48ProductionVisualBinder.cs'); const bootstrap=read('unity/VampPonUnity/Assets/_Project/Scripts/Runtime/U1Stage1SceneBootstrap.cs'); const catalog=read('unity/VampPonUnity/Assets/_Project/Resources/Production/U48/U48ProductionVisualCatalog.asset');
check(approved.entries.length===46&&approved.productionConnectedCount===46&&approved.runtimeApprovedCount===0&&approved.entries.every((e:any)=>e.productionConnected===true&&e.runtimeApproved===false),'46 connected awaiting runtime verification');
check(provider.includes('AssetApprovalLevel.Production')&&provider.includes('IsProductionApproved => true')&&provider.includes('U48ProductionVisualCatalog.LoadRequired()'),'production provider');
check(!provider.includes('Environment.GetEnvironmentVariable')&&!binder.includes('Environment.GetEnvironmentVariable')&&binder.includes('#if VAMPPON_U48_ASSET_PREVIEW\n            if (U48AssetPreviewProvider.IsSessionActive)'), 'no production preview/environment dependency; guarded preview isolation');
check(bootstrap.includes('U48ProductionVisualBinder.Attach(gameObject);')&&bootstrap.indexOf('U48ProductionVisualBinder.Attach(gameObject);')<bootstrap.indexOf('#if VAMPPON_U48_ASSET_PREVIEW\n            U48AssetPreviewSceneBinder'),'production binder outside preview guard');
check((catalog.match(/assetGroup:/g)??[]).length===46,'serialized catalog 46 entries');
for(const entry of approved.entries){check(catalog.includes(`assetGroup: ${entry.assetGroup}`)&&catalog.includes(`guid: ${entry.productionGuid}`),`${entry.assetGroup} serialized production reference`)}
const selectedIds=new Set(approved.entries.map((e:any)=>e.candidateId)); const runtimeSources=[provider,binder,bootstrap,catalog].join('\n');
const allCandidates=json('docs/design-targets/generated/unity-u48/approval-pack/approval-manifest.json').assetGroups.flatMap((g:any)=>g.candidates.map((c:any)=>c.candidateId));
check(allCandidates.filter((id:string)=>!selectedIds.has(id)&&runtimeSources.includes(id)).length===0,'non-selected candidate IDs unreachable');
check(readiness.approvedProductionAssetSetAvailable===true&&readiness.productionVisualAssetProviderConnected===true&&readiness.runtimeVisualReady===false&&readiness.simulatorReady===false,'readiness boundary');
for(const path of ['unity/VampPonUnity/Assets/_Project/Scripts/Runtime/Gameplay/GameplayServices.cs','unity/VampPonUnity/Assets/_Project/Scripts/Runtime/Gameplay/Stage1GameplayRuntimeCoordinator.cs','unity/VampPonUnity/Assets/_Project/Scripts/Runtime/Gameplay/State/RunGameplayState.cs'])check(!execFileSync('git',['diff','52b2267a','--',path],{cwd:root,encoding:'utf8'}),`${path} gameplay contract unchanged`);
console.log('U48 production visual connection check passed: gameplay=16, UI=30, selected references=46, non-selected=0, preview dependency=0, runtime verification pending.');
