import type { AssetManifestEntry } from './assetManifest';

const ROOT = '/assets/ui/battle-hud/processed';

export const BATTLE_HUD_UI_ASSET_KEYS = {
  ultimateSealLanternButton: 'battle_hud_ultimate_seal_lantern_button',
  kokuyouBottleFrame: 'battle_hud_kokuyou_bottle_frame',
  kokuyouBottleLabelRuntime: 'battle_hud_kokuyou_bottle_label_runtime',
  inventoryPaperSlot: 'battle_hud_inventory_paper_slot',
  dualGaugeFrame: 'battle_hud_dual_gauge_frame',
  paperTagLv: 'battle_hud_paper_tag_lv',
  paperTagDawn: 'battle_hud_paper_tag_dawn',
  paperTagCurrency: 'battle_hud_paper_tag_currency',
  paperTagMenu: 'battle_hud_paper_tag_menu',
  memoryStreetProgressFrame: 'battle_hud_memory_street_progress_frame',
  ultimateButtonLabel: 'battle_hud_ultimate_button_label',
} as const;

export const battleHudUiAssetEntries: AssetManifestEntry[] = [
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.ultimateSealLanternButton,
    path: `${ROOT}/battle-hud-ultimate-seal-lantern-button-runtime.png`,
    width: 188,
    height: 184,
    kind: 'ui',
    description: 'Battle HUD 右下必殺ボタンruntime版。封蝋とランタン。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.kokuyouBottleFrame,
    path: `${ROOT}/battle-hud-kokuyou-bottle-frame-runtime.png`,
    width: 140,
    height: 276,
    kind: 'ui',
    description: 'Battle HUD 左下黒曜瓶ゲージ枠runtime版。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.kokuyouBottleLabelRuntime,
    path: `${ROOT}/battle-hud-kokuyou-bottle-label-runtime.png`,
    width: 216,
    height: 54,
    kind: 'ui',
    description: 'Battle HUD 黒曜瓶ゲージ下部ラベルruntime版。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.inventoryPaperSlot,
    path: `${ROOT}/battle-hud-inventory-paper-slot-runtime.png`,
    width: 120,
    height: 148,
    kind: 'ui',
    description: 'Battle HUD 下部インベントリ紙カードslot runtime版。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.dualGaugeFrame,
    path: `${ROOT}/battle-hud-dual-gauge-frame-runtime.png`,
    width: 232,
    height: 92,
    kind: 'ui',
    description: 'Battle HUD HP/EXP 2段ゲージ外枠runtime版。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.paperTagLv,
    path: `${ROOT}/battle-hud-paper-tag-lv-v1.png`,
    width: 1122,
    height: 1402,
    kind: 'ui',
    description: 'Battle HUD LV紙札。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.paperTagDawn,
    path: `${ROOT}/battle-hud-paper-tag-dawn-v1.png`,
    width: 1122,
    height: 1402,
    kind: 'ui',
    description: 'Battle HUD Dawn in紙札。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.paperTagCurrency,
    path: `${ROOT}/battle-hud-paper-tag-currency-v1.png`,
    width: 1536,
    height: 1024,
    kind: 'ui',
    description: 'Battle HUD 通貨/Shard紙札。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.paperTagMenu,
    path: `${ROOT}/battle-hud-paper-tag-menu-v1.png`,
    width: 1122,
    height: 1402,
    kind: 'ui',
    description: 'Battle HUD menu紙札。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.memoryStreetProgressFrame,
    path: `${ROOT}/battle-hud-memory-street-progress-paper-v1.png`,
    width: 2172,
    height: 724,
    kind: 'ui',
    description: 'Battle HUD Memory Street進行バー。',
    required: false,
    fallback: true,
  },
  {
    id: BATTLE_HUD_UI_ASSET_KEYS.ultimateButtonLabel,
    path: `${ROOT}/battle-hud-ultimate-button-label-v1.png`,
    width: 2172,
    height: 724,
    kind: 'ui',
    description: 'Battle HUD 必殺ボタン下ラベル。',
    required: false,
    fallback: true,
  },
];
